config/routes.rb
Rails.application.routes.draw do

  
  
  resources :users, only: [:new, :create, :index] do
    collection do
      get :login
      post :post_login # Not sure if this is actually needed. Need to check.
      get :logout
    end
  end
  
  resources :trades do 
    get 'delete', :on => :member
  end
  
  resources :manage, only: [:add_transaction, :create, :delete_transaction, :remove]
  

  root 'display#home'
  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :login, presence: true
  validates :login, uniqueness: true
  validates :password, confirmation: true, presence: true
  validates :password_confirmation, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
  
  def password
    @password
  end

  def password=(password)
    @password = String.new(password)
    salt = SecureRandom.hex(20)
    salted_password = password.concat salt

    self.password_digest = Digest::SHA2.hexdigest(salted_password)
    self.salt = salt
    self.save
  end

  def password_valid?(password)
    salted_password = String.new(password + self.salt)
    password_digest = Digest::SHA2.hexdigest(salted_password)
    if password_digest == self.password_digest then
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    unless session[:current_user_id].nil? then
      flash[:error] = "Please log out before attempting to log in."
      redirect_to url_for(controller: :display, action: :home)
    end
  end

  def logout
    session[:current_user_id] = nil
    redirect_to login_users_path
  end

  def new

    # Comment the next line when in production
    @user = User.new

    # Uncomment the next six lines when in production
    # if session[:current_user_id].nil? then
        # flash[:error] = "You must be logged in."
        # redirect_to login_users_path
    # else
      # @user = User.new
    # end
  end

  def post_login
    user = User.find_by_login params[:login]
    if user && user.password_valid?(params[:password]) then
      session[:current_user_id] = user.id
      session[:user_first_name] = user.first_name
      redirect_to url_for(controller: :display, action: :home)
    else
      flash[:error] = "Username and/or password is incorrect."
      redirect_to login_users_path
    end
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params(params[:user]))
    if @user.save then
      redirect_to users_path
    else
      render new_user_path
    end
  end

  private
  def user_params(params)
    return params.permit(:first_name, :last_name, :login, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="error">
      <%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li>
        <%= msg + "." %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render partial: "errors" %>
<%= form_for @user do |f| %>
  <div class="field_container">
    <%= f.label("First name:") %>
    <%= f.text_field :first_name %>
    <br />
  </div>
  <div class="field_container">
    <%= f.label("Last name:") %>
    <%= f.text_field :last_name %>
    <br />
  </div>
  <div class="field_container">
    <%= f.label("Login:") %>
    <%= f.text_field :login %>
    <br />
  </div>
  <div class="field_container">
    <%= f.label("Enter a password:") %>
    <%= f.password_field :password %>
    <br />
  </div>
  <div class="field_container">
    <%= f.label("Confirm password:") %>
    <%= f.password_field :password_confirmation %>
    <br />
  </div>
  <br />
  <%= f.submit "Create User" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.login %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<%= form_tag(post_login_users_path, method: "post") do %>
  <div>
  	<%= label_tag(:login, "Username:") %>
  	<%= text_field_tag(:login) %>
  	<br />
  	<%= label_tag(:password, "Password:") %>
  	<%= password_field_tag(:password) %>
  	<br />
  </div>
  <br />
  <%= submit_tag("Log In") %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>